# Generated by Django 2.2.16 on 2022-02-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
