# Generated by Django 2.2.16 on 2022-02-02 06:44

from django.db import migrations, models


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        post.created = '%s' % (post.pub_date)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.RunPython(combine_names)
    ]
