# Generated by Django 2.2.16 on 2022-02-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
