# Generated by Django 2.2.16 on 2022-02-04 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.AddField(
            model_name='follow',
            name='author',
            field=models.ManyToManyField(help_text='Подписан на', null=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на'),
        ),
    ]
